//! Embedded flag-icons 7.3.2 assets (MIT); see assets/flags/LICENSE.

pub(crate) fn svg(code: &str) -> Option<&'static [u8]> {
    Some(match code {
        "AE" => include_bytes!("../assets/flags/ae.svg"),
        "AM" => include_bytes!("../assets/flags/am.svg"),
        "AR" => include_bytes!("../assets/flags/ar.svg"),
        "AT" => include_bytes!("../assets/flags/at.svg"),
        "AU" => include_bytes!("../assets/flags/au.svg"),
        "AZ" => include_bytes!("../assets/flags/az.svg"),
        "BE" => include_bytes!("../assets/flags/be.svg"),
        "BG" => include_bytes!("../assets/flags/bg.svg"),
        "BH" => include_bytes!("../assets/flags/bh.svg"),
        "BR" => include_bytes!("../assets/flags/br.svg"),
        "CA" => include_bytes!("../assets/flags/ca.svg"),
        "CH" => include_bytes!("../assets/flags/ch.svg"),
        "CL" => include_bytes!("../assets/flags/cl.svg"),
        "CN" => include_bytes!("../assets/flags/cn.svg"),
        "CO" => include_bytes!("../assets/flags/co.svg"),
        "CR" => include_bytes!("../assets/flags/cr.svg"),
        "CY" => include_bytes!("../assets/flags/cy.svg"),
        "CZ" => include_bytes!("../assets/flags/cz.svg"),
        "DE" => include_bytes!("../assets/flags/de.svg"),
        "DK" => include_bytes!("../assets/flags/dk.svg"),
        "EC" => include_bytes!("../assets/flags/ec.svg"),
        "EE" => include_bytes!("../assets/flags/ee.svg"),
        "EG" => include_bytes!("../assets/flags/eg.svg"),
        "ES" => include_bytes!("../assets/flags/es.svg"),
        "FI" => include_bytes!("../assets/flags/fi.svg"),
        "FR" => include_bytes!("../assets/flags/fr.svg"),
        "GB" => include_bytes!("../assets/flags/gb.svg"),
        "GE" => include_bytes!("../assets/flags/ge.svg"),
        "GH" => include_bytes!("../assets/flags/gh.svg"),
        "GR" => include_bytes!("../assets/flags/gr.svg"),
        "GT" => include_bytes!("../assets/flags/gt.svg"),
        "HK" => include_bytes!("../assets/flags/hk.svg"),
        "HR" => include_bytes!("../assets/flags/hr.svg"),
        "HU" => include_bytes!("../assets/flags/hu.svg"),
        "ID" => include_bytes!("../assets/flags/id.svg"),
        "IL" => include_bytes!("../assets/flags/il.svg"),
        "IN" => include_bytes!("../assets/flags/in.svg"),
        "IS" => include_bytes!("../assets/flags/is.svg"),
        "IT" => include_bytes!("../assets/flags/it.svg"),
        "JO" => include_bytes!("../assets/flags/jo.svg"),
        "JP" => include_bytes!("../assets/flags/jp.svg"),
        "KE" => include_bytes!("../assets/flags/ke.svg"),
        "KG" => include_bytes!("../assets/flags/kg.svg"),
        "KR" => include_bytes!("../assets/flags/kr.svg"),
        "KW" => include_bytes!("../assets/flags/kw.svg"),
        "KZ" => include_bytes!("../assets/flags/kz.svg"),
        "LB" => include_bytes!("../assets/flags/lb.svg"),
        "LT" => include_bytes!("../assets/flags/lt.svg"),
        "LV" => include_bytes!("../assets/flags/lv.svg"),
        "MA" => include_bytes!("../assets/flags/ma.svg"),
        "MD" => include_bytes!("../assets/flags/md.svg"),
        "MX" => include_bytes!("../assets/flags/mx.svg"),
        "MY" => include_bytes!("../assets/flags/my.svg"),
        "MZ" => include_bytes!("../assets/flags/mz.svg"),
        "NG" => include_bytes!("../assets/flags/ng.svg"),
        "NL" => include_bytes!("../assets/flags/nl.svg"),
        "NO" => include_bytes!("../assets/flags/no.svg"),
        "NZ" => include_bytes!("../assets/flags/nz.svg"),
        "OM" => include_bytes!("../assets/flags/om.svg"),
        "PA" => include_bytes!("../assets/flags/pa.svg"),
        "PE" => include_bytes!("../assets/flags/pe.svg"),
        "PH" => include_bytes!("../assets/flags/ph.svg"),
        "PK" => include_bytes!("../assets/flags/pk.svg"),
        "PL" => include_bytes!("../assets/flags/pl.svg"),
        "PT" => include_bytes!("../assets/flags/pt.svg"),
        "QA" => include_bytes!("../assets/flags/qa.svg"),
        "RO" => include_bytes!("../assets/flags/ro.svg"),
        "RS" => include_bytes!("../assets/flags/rs.svg"),
        "RU" => include_bytes!("../assets/flags/ru.svg"),
        "SA" => include_bytes!("../assets/flags/sa.svg"),
        "SE" => include_bytes!("../assets/flags/se.svg"),
        "SG" => include_bytes!("../assets/flags/sg.svg"),
        "SI" => include_bytes!("../assets/flags/si.svg"),
        "SK" => include_bytes!("../assets/flags/sk.svg"),
        "SV" => include_bytes!("../assets/flags/sv.svg"),
        "TH" => include_bytes!("../assets/flags/th.svg"),
        "TJ" => include_bytes!("../assets/flags/tj.svg"),
        "TN" => include_bytes!("../assets/flags/tn.svg"),
        "TR" => include_bytes!("../assets/flags/tr.svg"),
        "TW" => include_bytes!("../assets/flags/tw.svg"),
        "TZ" => include_bytes!("../assets/flags/tz.svg"),
        "UA" => include_bytes!("../assets/flags/ua.svg"),
        "UG" => include_bytes!("../assets/flags/ug.svg"),
        "US" => include_bytes!("../assets/flags/us.svg"),
        "UY" => include_bytes!("../assets/flags/uy.svg"),
        "UZ" => include_bytes!("../assets/flags/uz.svg"),
        "VE" => include_bytes!("../assets/flags/ve.svg"),
        "VN" => include_bytes!("../assets/flags/vn.svg"),
        "ZA" => include_bytes!("../assets/flags/za.svg"),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    #[test]
    fn every_country_has_a_parseable_flag() {
        for entry in crate::COUNTRY_CODES {
            let bytes = super::svg(entry.code).expect(entry.code);
            let document = roxmltree::Document::parse(std::str::from_utf8(bytes).unwrap()).unwrap();
            assert_eq!(document.root_element().tag_name().name(), "svg");
        }
        assert!(super::svg("XX").is_none());
    }
}
