[package]
name = "ltbox-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
aes = { workspace = true }
cbc = { workspace = true }
sha2 = { workspace = true }
digest = { workspace = true }
ureq = { workspace = true }
roxmltree = { workspace = true }
moka = { workspace = true }
dirs = { workspace = true }
semver = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
tempfile = "3"
